title: Welcome to my github Pages!
author: GitHub User Owen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm glad that I am enabled to establish a new blog of my own.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
